### PR TITLE
FindPatternAsync

### PR DESCRIPTION
**Pull request by dnnyy**
Fix for async FindPattern.

### CODE REVIEW

**Comment by Rob--** [comment]
Thanks for your contribution! Should really create some tests for this library.

**Comment by dnnyy** [comment]
You're welcome! Yes I was just experimenting with game hacking and found out about pattern scanning for getting offsets dynamically and noticed something is broken. I haven't used an older version of memoryjs but according to the readme previous versions didn't make use of the handle explicitly. These bugs probably occoured because of these changes (num of args) so it's not a big deal, everyone does such mistaked. But really really big thanks for this library, its freaking insane. :) You did so much work on it's so insane what you did. :>

Offtopic: Currently installing and testing napajs, it may works well with your library but I have to see. The problem using nodejs for a hack is weird because it still runs single threaded and setInterval for function calls work, but for something like a knife changer the latency is too high so a inifnite loop has to be used for certain tasks. Asynchronous functions just make use of not blocking the code but it does not solve the problem of code which has to be run parallel. Any ideas for that maybe?:>Maybe you have some ideas tho :P
It your interested whether napajs works good or if I found any good solution to that problem, message me back! :)

regards

**Comment by Rob--** [comment]
Yep, when I made the upgrade to 3.0 I forgot to make look over the index.js and change the number of args etc which is why I said I should probably create some tests haha! And thank you so much, it's amazing to see people really appreciate my work :)

Is the knife changer for CSGO or CSS? Could never get one to work on CSGO :( skin changer always worked perfectly, however recently when I try to force an update (write m_nDeltaTick to -1) it crashes the game.

You could always look into [clusters](https://nodejs.org/api/cluster.html)? You could fork until you have 3-4 processes (or a separate process for each hack feature) and then assign each process a certain hack facility (e.g. aimbot on one process, knive/skin changer on another). I've also got a library called [cluster-message](https://github.com/Rob--/cluster-messages) that you can user to send messages to the child processes (e.g. to report hack status, enable/disable hack). If you have any more questions feel free to ask!

**Comment by Rob--** [comment]
I'll reply to your message on Discord, add me i7xx#9784

**Pull request merged**
